version: '2.2'

services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge

  app:
      restart: always
      build: .
      network_mode: bridge
      links:
        - 'redis:redis'
      env_file:
        - .env
      environment:
          WEBROOT: /var/www
          WEBROOT_PUBLIC: /var/www/public
          COMPOSER_INSTALL_ON_BUILD: 1
          LARAVEL_APP: 1
          RUN_LARAVEL_SCHEDULER: 0
          RUN_LARAVEL_MIGRATIONS_ON_BUILD: 1
          PRODUCTION: 1
          PHP_MEMORY_LIMIT: 512M
          PHP_POST_MAX_SIZE: 50M
          PHP_UPLOAD_MAX_FILESIZE: 20M
          VIRTUAL_HOST: whoami.local
      volumes:
        - ${DATA_PATH_HOST}/storage:/var/www/storage/app
        - ${DATA_PATH_HOST}/logs:/var/www/storage/logs
      depends_on:
        - redis

  redis:
      container_name: redis
      network_mode: bridge
      image: redis:alpine
      volumes:
          - ${DATA_PATH_HOST}/redis:/data

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
